# AVB handling on non A/B devices with dedicated recovery partition
BOARD_AVB_RECOVERY_KEY_PATH := user-keys/avb.pem
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1
